### ISSUE TITLE
Fix not working apps

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#10]
Right now the apps are starting, but it seems the actual functions of most apps are not working.

Please help to make get them working.

**Comment by djmgit** [comment]
Hi mario
I was looking into this problem and I found this:
The apps are using loklak api by making angular http request using url /api/....
For example the app querybrowser makes the following request :
/api/suggest.json?count=10000&order=desc&orderby=query_count

Now my point is here root is apps.loklak,org
So the request url is apps.loklak.org/api/suggest.json?count=10000&order=desc&orderby=query_count
however when I am firing this up in my browser i am getting 404 error
This might be the problem, although I may be wrong

Well I found another thing, when I am trying to make an angular http request to loklak api, I am getting error with status code 0 which signifies CORS issue.

**Comment by mariobehling** [comment]
@djmgit apps.loklak.org is just a frontend. In order to make the apps work we need to make the queries to http://api.loklak.org. 

In your example it would be http://api.loklak.org/api/suggest.json?count=10000&order=desc&orderby=query_count

If the CORS issue persists, please open a separate issue in loklak server for this. Cheers!

**Comment by Abhi2424shek** [comment]
@mariobehling it would be nice if you specified which all apps doesnot work on the issue description and add check boxes!

**Comment by Orbiter** [comment]
all api requests must now use the callback operator to force a jsonp result, like:
http://api.loklak.org/api/search.json?timezoneOffset=-60&q=linux&callback=p
