### ISSUE TITLE
Delete daminisatya-patch-1 branch

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/apps.loklak.org#112]
@daminisatya is that branch still needed, no i guess. Putting non working branches is a bad way to work, I hope github web created that branch for you, so now let's remove it, isn't that unneeded.

**Comment by yukiisbored** [comment]
@daminisatya is one of the core developers of Loklak. She has the rights to wheter have her own development branch inside this repository or have it in her fork.

**Comment by daminisatya** [comment]
@Abhi2424shek @yukiisbored  I deleted the branches, closing the issue now! Cheers!
