### ISSUE TITLE
Reorganize apps and delete irrelevant ones

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#12]
Please re-organize the apps into the following categories:

* [x] Accounts
* [x] Games
* [x] Scraper
* [x] Search
* [x] Internet of Things
* [x] Visualizers

Delete the following:
* [x] Susi

**Comment by Marauderer97** [comment]
@mariobehling i would like to try working on this.

**Comment by Marauderer97** [comment]
@mariobehling  I have organized the apps into the categories you wanted(to the best of my understanding of them), but I am not sure where exactly a few apps go. Certain apps like histogram seem to come under Visualization and Scraper, and I wasn't entirely sure about what to include under the Internet of Things. Here is what I have done, tell me if you find it alright, I will make a PR. Thanks :)
ACCOUNTS
![image](https://cloud.githubusercontent.com/assets/20185076/21480889/b303fca2-cb87-11e6-8bc5-b4c7f49d6222.png)
GAMES
![image](https://cloud.githubusercontent.com/assets/20185076/21480908/fa8b5c8c-cb87-11e6-921a-3dab306dbe88.png)
SCRAPER
![image](https://cloud.githubusercontent.com/assets/20185076/21480917/132e4b6e-cb88-11e6-8cae-965b4e1a1780.png)
SEARCH
![image](https://cloud.githubusercontent.com/assets/20185076/21480928/2caad864-cb88-11e6-8f9a-2e6ca3929af4.png)
VISUALIZERS
![image](https://cloud.githubusercontent.com/assets/20185076/21480934/3fd58e16-cb88-11e6-9596-7218f833789c.png)
INTERNET OF THINGS
![image](https://cloud.githubusercontent.com/assets/20185076/21480937/597b706a-cb88-11e6-96aa-43f07df1539e.png)

**Comment by mariobehling** [comment]
Thank you. Please make a PR and we will see. We can go step by step.

**Comment by Marauderer97** [comment]
@mariobehling Understood. Sorry for the misunderstanding. So, since they are already some categories, you want me to create the ones that aren't mentioned and remove categories like SUSI API? 
Also since the categories are called from http://loklak.org/api/apps.json, where will I have to make the changes?

**Comment by Marauderer97** [comment]
@mariobehling I have gone through the entire source code but I cannot find where the apps.json file that the api returns is being strored, I have also tried searching in loklak/loklak_server, but the api folder doesn't have any such json files, what should I try doing next?

**Comment by Marauderer97** [comment]
@mariobehling I think we have two options, either we store the final json file and ask the users to update it each time they create a new app, 
or we try and mimic loklak_server, to auto-generate our own apps.json file, from where we will fetch categories.
What do you think we should do?
