### ISSUE TITLE
Enhance site design and menus

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#13]
Please take out the the following from the top right bar:
* [x] Architecture, Download, Tutorials, Apps

On the left sidebar bottom:
* [x] Change "Read the loklak app primer to learn how you can contribute a loklak app!" to "Contribute your app on [GitHub](http://github.com/fossasia/apps.loklak.org)!"

On the top left change:
* [x] loklak.org into "lolak apps"
* [x] Take out "app list"

On main content area:
* [x] Take out loklak apps

**Comment by Heredroky** [comment]
@mariobehling I want to work on this issue

**Comment by Heredroky** [comment]
@mariobehling How can I run this locally?

**Comment by Heredroky** [comment]
@mariobehling I don't know how to run this locally, can you help me please?

**Comment by mariobehling** [comment]
@Heredroky Please try one of the following here: http://stackoverflow.com/questions/29528922/how-to-create-a-localhost-server-to-run-an-angularjs-project

**Comment by adarsh-ideal** [comment]
@mariobehling Just tried to fix this.
Please check the Pull Request, is that what you are expecting?

**Comment by Heredroky** [comment]
Sorry, but I claimed this issue first

**Comment by Heredroky** [comment]
I have been working on it, then, it would be unfair

**Comment by mariobehling** [comment]
* "Change "Read the loklak app primer to learn how you can contribute a loklak app!" to "Contribute your app on GitHub!"" is not readable
*  Take out "app list"
* On main content area:  Take out loklak apps

**Comment by Heredroky** [comment]
@mariobehling I solves the 2 first points. Taking out loklak apps, will make it fail

**Comment by Heredroky** [comment]
@mariobehling at least, merge #29, it would be a progress

**Comment by rhemon** [comment]
@mariobehling @Heredroky for menus i also suggest these:

- "Home" links to the page where apps are listed
- "About" we should have a simple about page and link to that, instead of linking to loklak.org 
- "API" is fine i guess, but we could also redirect to api.loklak.org?
