### ISSUE TITLE
Change site design to lighter theme

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#14]
The site design is currently in a dark theme. Please change the site design to follow the design at http://loklak.fossasia.org

**Comment by nikhilrayaprolu** [comment]
![screenshot from 2016-12-26 01-15-46](https://cloud.githubusercontent.com/assets/15216503/21472616/ebc32c2c-cb08-11e6-957a-5ab948446e3f.png)

@mariobehling How is this theme looking?

**Comment by mariobehling** [comment]
Thanks. Good progress. Please help us to follow the design to http://loklak.fossasia.org more closely e.g. gray top bar, black color links, standard colored scroll bars. Cheers.

**Comment by adarsh-ideal** [comment]
@mariobehling Is there something else needed to be done here, sir?

**Comment by mariobehling** [comment]
Please change "loklak apps" on the top left:
* [ ] make "loklak" itself into the pink color
* [ ] make the scroll over color as follows: make the pink color for loklak slight brighter and change "Apps" to a lighter gray (instead of white)

**Comment by adarsh-ideal** [comment]
Yes sir, I'll do it.
