### ISSUE TITLE
Create Github Issue creation and Pull request template

### ISSUE THREAD

**Issue by kavithaenair** [fossasia/apps.loklak.org#153]
### Short Description
Create templates for issue creation and pull request as in loklak_server.

**Comment by kavithaenair** [comment]
I'll work on this

**Comment by daminisatya** [comment]
@kavithaenair Please mention what you are going to include in the template

**Comment by kavithaenair** [comment]
@daminisatya i'll follow the template provided in loklak_server. Is that fine?

**Comment by daminisatya** [comment]
Ok sure 👍

**Comment by daminisatya** [comment]
Follow whats given in susi android repo too

**Comment by kavithaenair** [comment]
okay @daminisatya 👍 😄
