### ISSUE TITLE
Fix site and apps display

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#2]
The loklak apps have been moved from the loklak server to the apps repository.

Some links and service connections are broken therefore. Please help to fix them and get the site working at http://apps.loklak.org

**Comment by sanchittechnogeek** [comment]
Please check this pull request
https://github.com/fossasia/apps.loklak.org/pull/4

**Comment by mariobehling** [comment]
Thanks! So next, we need to get the apps working.

**Comment by adarsh-ideal** [comment]
I want to work on this.
While checking this, I found that the links are not pointing to the apps and this can be solved by putting right path in index.html

Please take a look at the pull-request: https://github.com/fossasia/apps.loklak.org/pull/6

**Comment by sanchittechnogeek** [comment]
@adarsh-ideal Thanks! ,  @mariobehling  you can merge #6 PR

**Comment by adarsh-ideal** [comment]
Don't thank. It's what we are supposed to do. :-)
