### ISSUE TITLE
Emoji Heatmapper

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#204]
Please add an easier way to chose emoji similar to many other app e.g. Facebook, Google Chat/Gmail etc.
![screenshot from 2017-06-21 09-41-25](https://user-images.githubusercontent.com/1583873/27372749-f04adf0e-5665-11e7-982f-e109dbb2a271.png)

**Comment by kavithaenair** [comment]
👍  @mariobehling
