### ISSUE TITLE
Different top bar and sidebar properties across app

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#207]
The top bar of the start screen has a different height to the top bar of the app screen. The sidebar is also missing info - "contribute on github" - in the app screen.

Please use the same components across the app as much as possible, e.g. can you check if you can use the same sidebar as in the start screen and just control the colors with javascript? What options are available?
![screenshot from 2017-06-21 10-06-41](https://user-images.githubusercontent.com/1583873/27373767-d8330582-5669-11e7-9615-3864283d4264.png)

**Comment by djmgit** [comment]
@mariobehling I am looking into it.
