### ISSUE TITLE
Create Movie Tweets App

### ISSUE THREAD

**Issue by kavithaenair** [fossasia/apps.loklak.org#263]
- Issue type: Feature request

### Short description
Add a new app which shows movie tweets with statistics.
In the app movie tweets will be shown according to emotion of the tweets i.e., positive or negative comments the movie gets. Its shows review/reaction of people if the movie is good or bad by just typing the name of the movie. Usually we follow few movie websites for review instead we can directly get review of people in this loklak movie review app.   

Am going to do this by  using search.json and also will try to add country wise emotion statistics using new classifier.json API.

### Would you like to work on the issue?
Yes

**Comment by mariobehling** [comment]
This description is too basic. What are you actually trying to do? Please provide a detailed description that could go on the apps page as well. Please avoid too be too superficial. Provide sufficient information.

**Comment by kavithaenair** [comment]
@mariobehling Description is updated now.
