### ISSUE TITLE
App list is not loaded from apps.loklak.org

### ISSUE THREAD

**Issue by rhemon** [fossasia/apps.loklak.org#27]
Presently in the home page, all the apps in the repository is not shown. I think this is happening because  in app_list.js its loading data from loklak.org
```
$http.jsonp('http://loklak.org/api/apps.json?callback=JSON_CALLBACK')
    .success(function(data, status, headers, config) {
        $scope.categoryKeys = data.categories;
        $scope.apps = data.apps;
        $scope.categoryKeys.unshift('All');
    });
```
this doesn't load the apps that are only here. the fix that I can think of is to have a json file where the app name and the directory for it will be entered:
```
[
{
    "name": "app name",
    "dir": "directory-name/" 
}
]
```
and then using that we can have the apps.json generated from the apps in apps.loklak.org, that way rest of the code can be kept same.  

If its ok, I would like to try fixing this.

**Comment by Marauderer97** [comment]
@rhemon Every app already has a file like this app.json, with a category name and an application name, loklak_server already has a mechanism of integrating all such app.json files into a single json file from where the data is fetched. We just have to include that mechanism in this apps.loklak.org

**Comment by rhemon** [comment]
yeah I know that every file has app.json, but the thing is that the apps.json generated by loklak server only includes the the apps in loklak server, not the ones to apps.loklak.org 
now I mentioned about having another json file so that I can use that to read all the other app.json file. there are other ways to approach that but as a beginner thats one easy way I could think of, since I can simply use javascript & angular to do that

**Comment by Marauderer97** [comment]
@rhemon sounds good!
One clarification though, are you saying each app should have another json file and you will integrate all of them using json and angular, or you want to create a new json file that has all the apps stored in it? If it is the later, then I have already implemented it locally, and we can simply use that code..

**Comment by rhemon** [comment]
no not for each app, but a json file in the root folder that will simply have the dirs listed so that I can use that to know which dirs to check for app.json @Marauderer97 if you have already done it, then yeah go ahead and do the PR then

**Comment by Marauderer97** [comment]
@rhemon What I am doing is this, simply storing the categories json data that we require, which will have to be updated, each time we create a new app
![image](https://cloud.githubusercontent.com/assets/20185076/21709538/ae1611fc-d407-11e6-998c-471629914261.png)
@mariobehling what do you think?

**Comment by mariobehling** [comment]
@Marauderer97 Oh, I like this approach very much.

**Comment by rhemon** [comment]
yeah thats better, it also resolves the category issue :+1:

**Comment by rhemon** [comment]
while you are at it, if its ok, can the apps be brought into one directory rather than having them in the root directory of the project?. its just my personal opinion, i dont know why but I find it very annoying to see all that folder in the root directory. this is just a opinion and not an issue :P

**Comment by mariobehling** [comment]
@rhemon

>  apps be brought into one directory 

If not, open an issue for it.

**Comment by mariobehling** [comment]
Seems like all apps are on the site already. Thanks!
