### ISSUE TITLE
Add error info and dark theme to map in CountryTweetMap app

### ISSUE THREAD

**Issue by djmgit** [fossasia/apps.loklak.org#272]
Add error notifications for invalid input in CountryTweetMap app. Also add other themes to map so that users can switch between them.

**Comment by djmgit** [comment]
I am working on this.

**Comment by mariobehling** [comment]
@djmgit Can we avoid themese on the app page, please? It would not make sense, if each app can have different themes. We should rather go into the direction to provide info how to plugin the "loklak apps" to websites. The goal of the apps page should be also to provide folks with a way to use the apps on their own site. Therefore themes have a lower priority and should be taken out.
