### ISSUE TITLE
Not seeing results on EmojiHeatMap

### ISSUE THREAD

**Issue by anshumanv** [fossasia/apps.loklak.org#340]
- Issue type: Bug report

### Short description
I was just trying emojiheatmap app and didn't see any results, can you please clarify if there are any special instructions for using it?

### Environment

 - Operating system: Linux Mint 18.2
 - Software version: Chrome 62

### Steps to reproduce
1. Visit https://apps.loklak.org/emojiHeatmapper/emoji-map.html and use the app.

### Screenshots of the issue
![image](https://user-images.githubusercontent.com/21009455/34356219-1078508c-ea62-11e7-8320-c4bd7c2777ec.png)

### Expected behaviour
App should display results.

### Actual behaviour
No results obtained.

### Description
Not seeing the results on the loklak emojiheatmap app.

### Would you like to work on the issue?
Sure

**Comment by anshumanv** [comment]
@kavithaenair perhaps, can you see if the issue is valid?

**Comment by kavithaenair** [comment]
hey @anshumanv , you have to load the scripts as to see the results.
![image](https://user-images.githubusercontent.com/18421291/34357564-3ee980a6-ea6e-11e7-9b85-7a9e5d61dd99.png)

**Comment by anshumanv** [comment]
Hey @kavithaenair thanks your quick response, can you please link me to the script which is to be loaded also can you guide me if there are any other additional steps to be followed?
That would be nice of you, thanks. :smile:

**Comment by anshumanv** [comment]
Okay, got it @kavithaenair, unsafe scripts are to be loaded to run it. Thanks! :smile:
