### ISSUE TITLE
Implement design closer to loklak.fossasia.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#35]
We have a search site on http://loklak.fossasia.org

Please take out the "blueish/pinkish" color and make the design closer to the loklak search site.

**Comment by djmgit** [comment]
@mariobehling Hi!, I would like to work on this bug.

**Comment by Abhi2424shek** [comment]
Go on then!

**Comment by mariobehling** [comment]
Please also change font of "loklak" to "Courier New".
