### ISSUE TITLE
Fix and Implement a nicer boilerplate app

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#38]
The boilerplate app was originally made when the apps where still part of loklak.org. Please enhance the app:
* [ ] Correct the links
* [ ] Do not show a top bar as part of the app
* [ ] Implement a style similar to http://loklak.fossasia.org
* [ ] Create a nice footer with a link to apps.loklak.org
* [ ] Link to the Readme.md of apps.loklak.org
* [ ] Update the screenshot of the app

**Comment by djmgit** [comment]
@mariobehling I would like to work on this, Please assign this bug to me.
