### ISSUE TITLE
Apps are broken due to wrong endpoint urls.

### ISSUE THREAD

**Issue by KukkadapuSushma** [fossasia/apps.loklak.org#43]
What i have noticed is : all apps are not able to give response due to the wrong api urls. They all are pointing to "apps.loklak.org"  instead of "api.loklak.org". @mariobehling

**Comment by KukkadapuSushma** [comment]
i would like to work on this issue @mariobehling !! :)

**Comment by daminisatya** [comment]
@KukkadapuSushma good catch :D Assigning it to you.

@mariobehling We missed this testing!
