### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#51]
* [x] Use same size and design for top left loklak icon as on http://loklak.net seach pages and use Courier New as a font
* [x] Use loklak in pink and apps in standard black color of top menu bar (not in capital letters)
* [x] Always write loklak in small (not capital letters) using Courier New
* [x] Link the top left loklak apps link to "./" home of the service (not loklak.org)
* [x] Implement top right menu bar items as follows (in same order)
  * [x] Home -> link to home of service
  * [x] Search -> http://loklak.net
  * [x] About -> http://loklak.net/about
  * [x] Blog -> http://blog.loklak.net
  * [x] Developers -> http://dev.loklak.org
  * [x] API -> http://api.loklak.org
* [x] On the left sidebar use the same gray color as on the top bar
* [ ] On the left sidebar ensure no item stays on with a gray background and blue link color

**Comment by djmgit** [comment]
@mariobehling I would like to work on this :)

**Comment by mariobehling** [comment]
@djmgit Thank you!
