### ISSUE TITLE
Change style of apps "moving in"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#59]
The apps are currently moving in from right to left, when a category is opened.

Please change the style to something less intruding.

Implement this feature in a way that it appears the apps are coming from the back or similar.

The goal is to have something that only shows a small movement and is quick.

**Comment by Marauderer97** [comment]
@mariobehling I'd like to try working on this
:smile:

**Comment by Marauderer97** [comment]
@mariobehling Currently the code uses the bootstrap class fadeInRight, a simple fadeIn will achieve what you want, but you can also opt for classes like zoomIn, it depends on how noticeable you want your effect to be?

**Comment by mariobehling** [comment]
@Marauderer97 should be a very small effect. Little noticeable..
