### ISSUE TITLE
Enhance design with new field design

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#64]
Please see screenshot below and enhance the design to match the screenshot with different gray areas.

![screenshot from 2017-01-11 04-12-06](https://cloud.githubusercontent.com/assets/1583873/21834806/6eeb5816-d7b8-11e6-9606-2a56efebd037.png)

**Comment by Marauderer97** [comment]
@mariobehling  I would like to work on this :)

**Comment by Marauderer97** [comment]
![image](https://cloud.githubusercontent.com/assets/20185076/21890761/3f2337b4-d8f5-11e6-8d2d-ddb234fedae0.png)
Is this satisfactory? @mariobehling

**Comment by daminisatya** [comment]
@Marauderer97 Can you explain me what changes you have made? I can see a significant color difference which is not all in sync.

**Comment by mariobehling** [comment]
@Marauderer97 Good progress!

Please help to get it a bit closer to the screenshot, e.g. in regards to the alignment of text and the implementation of the area below the menu bar.

Thank you.

**Comment by sudheesh001** [comment]
@Marauderer97 Please make the necessary corrections as pointed out. The goal of the task should be to be the same as the screenshot.

![3f2337b4-d8f5-11e6-8d2d-ddb234fedae0](https://cloud.githubusercontent.com/assets/4545925/21891105/2416e3de-d8e2-11e6-8c12-2621764c9970.png)

**Comment by Marauderer97** [comment]
Cool! I assumed that you only wanted the colours changed

**Comment by sudheesh001** [comment]
It'd be great help during our reviews if the details were read clearly. I am not sure how the assumption was made 😄 
> enhance the design to match the screenshot with different gray areas.

**Comment by Marauderer97** [comment]
@mariobehling @daminisatya Is this good?
![image](https://cloud.githubusercontent.com/assets/20185076/21902922/cc7f862a-d923-11e6-8238-a963215c6a04.png)

**Comment by Marauderer97** [comment]
@sudheesh001 I did read the details carefully, I interpreted it "match the screenshot with different gray areas"  as changing those specific areas to gray. It was a simple misunderstanding.

**Comment by mariobehling** [comment]
@Marauderer97 Looks nice. Can we test it somewhere?

Could you also do the following:
*  Left align "Categories"
*  In the row categories change "loklak apps" to "All Apps" otherwise it is too redundant

**Comment by sudheesh001** [comment]
This looks better, please give us a link where we could test it 😄

**Comment by Marauderer97** [comment]
@mariobehling @sudheesh001 
Made the requested changes.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/20185076/21922877/ecf9b858-d996-11e6-9744-329807ab2a15.png)

Test link: https://marauderer97.github.io/

**Comment by mariobehling** [comment]
@Marauderer97 Thank you. Please make two small changes:
* indent "Categories same as other items on the left side
* clicking on "All" menu item shows "loklak apps", please show "All apps" here as well

Please incorporate the other recent changes in the repo and make a PR.

Cheers.

**Comment by Marauderer97** [comment]
@mariobehling Done! 
https://marauderer97.github.io

**Comment by jig08** [comment]
The "About Project" Image preview seems to be broken.

<img width="1280" alt="screen shot 2017-01-13 at 2 06 18 pm" src="https://cloud.githubusercontent.com/assets/9291400/21931026/78929626-d999-11e6-8bca-3a26132ac627.png">

**Comment by Marauderer97** [comment]
@jig08 that isn't working in apps.loklak.org either. Do you want me to fix that in this PR too?

**Comment by daminisatya** [comment]
Yes please fix it and open a PR.

**Comment by Marauderer97** [comment]
@jig08 done! :)
https://marauderer97.github.io
