### ISSUE TITLE
Add a search feature to find apps

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#65]
Please add a simple search feature to find apps on the application as in screenshot below. Ensure it works on GitHub Pages.

![screenshot from 2017-01-11 04-12-061](https://cloud.githubusercontent.com/assets/1583873/21835129/d6623f30-d7ba-11e6-9d33-da340e89a9ff.png)

**Comment by djmgit** [comment]
@mariobehling I would like to work on this :)
