### ISSUE TITLE
Making "Loklak tweets Histogram app" generic

### ISSUE THREAD

**Issue by KukkadapuSushma** [fossasia/apps.loklak.org#69]
Now it’s collecting only fossasia tweets, I would like to enhance it and add : #anyTag & display histogram.
@mariobehling

**Comment by djmgit** [comment]
@KukkadapuSushma Are you still planning to work on this? If not I would like to take up this issue as no one is assigned currently :)

**Comment by KukkadapuSushma** [comment]
Yup I am still on it, but due to my previous issues I was unassigned! @djmgit

**Comment by djmgit** [comment]
okay! thats great :)

**Comment by mariobehling** [comment]
@KukkadapuSushma I see you are working on different issues and this could be a reason things are taking time. Please only claim one issue at a time.

@djmgit Maybe have a try and go for it as well.
