### ISSUE TITLE
Fixing the GPS device tracking app

### ISSUE THREAD

**Issue by djmgit** [fossasia/apps.loklak.org#70]
Presently the GPS device tracking app is just showing a blank white screen without any functionality

**Comment by djmgit** [comment]
I would like to work on this

**Comment by Abhi2424shek** [comment]
@djmgit pls go on

**Comment by jig08** [comment]
@djmgit Kindly take up one issue at a time. Resolve the previous assigned ones before this can be assigned to you. Cheers !

**Comment by djmgit** [comment]
@jig08 okay :)

**Comment by daminisatya** [comment]
@djmgit Can you help us fix the travis build failures?
