### ISSUE TITLE
Enhance top bar to match height and design of loklak.net

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#75]
At loklak.net the top bar has a different height. Please ensure the height and font size matches on apps.loklak.org.

Also ensure the design of the search box is identical with one difference: Please make the search box at apps.loklak.org shorter and but also include the pink search button.

![screenshot from 2017-01-13 16-20-41](https://cloud.githubusercontent.com/assets/1583873/21935074/4589679c-d9ac-11e6-8167-78be01624df2.png)

**Comment by Marauderer97** [comment]
@mariobehling Yeah! I would like to do this! :smile:

**Comment by Marauderer97** [comment]
![image](https://cloud.githubusercontent.com/assets/20185076/22023006/67328b4e-dcea-11e6-97a8-8efc255db235.png)
@mariobehling Does this look good?
