### ISSUE TITLE
Improve styling and add colored icons and overlay color to left hand menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#79]
The left hand menu only has gray areas currently. To improve we can simply take inspiration from material design and the Google Play store. Please implement a left hand menu bar similar to the screenshot below.

![screenshot from 2017-01-13 17-21-41](https://cloud.githubusercontent.com/assets/1583873/21936943/74de8a32-d9b5-11e6-9a4f-c07e172a2367.png)

**Comment by djmgit** [comment]
@mariobehling I would like to work on this :)

**Comment by Aniket965** [comment]
you want same like playstore or bit diffrent

**Comment by mariobehling** [comment]
@Aniket965 Play store is handling this in a kind of advanced way. So, just check what you can do for now and we can iterate from there.
