### ISSUE TITLE
Enhancing the search button experience by adding keyboard action across all the apps

### ISSUE THREAD

**Issue by KukkadapuSushma** [fossasia/apps.loklak.org#88]
I want to enhance search button experience, currently few apps search buttons are working only with mouse click action.  I would like to add keyboard action across all those apps. @mariobehling

**Comment by jig08** [comment]
Kindly take up one issue at a time, resolve the previous assigned ones before taking up a new one. Thanks :)

**Comment by daminisatya** [comment]
Let's get this in first!

**Comment by KukkadapuSushma** [comment]
https://github.com/fossasia/apps.loklak.org/pull/96
