### ISSUE TITLE
Take out Category "About Project" and "App list"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#92]
The category "About Project" is not hosting a working app. The category shows the app "App list" which is not working and this is not a standard app, but just a helper app to display other apps.

Therefore, please take out the About Project category and the app.

**Comment by Marauderer97** [comment]
@mariobehling yes I was going to suggest this myself. Will fix this.

**Comment by Abhi2424shek** [comment]
Sure go on @marauderer97
