### ISSUE TITLE
Add other existing apps to site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/apps.loklak.org#93]
Please add the following apps and ensure they are working with the service at api.loklak.org

* [x] https://github.com/fossasia/loklak-webtweets (Category: Misc)
* [ ] https://github.com/fossasia/loklak_tweetheatmap (Category: Visualizer)
* [x] https://github.com/fossasia/loklak_movietweets  (Category: Search)
* [ ] https://github.com/fossasia/loklak_heatmap (Category: Visualizer)
* [x] https://github.com/fossasia/loklak_heatmapper (Category: Visualizer)
* [ ] https://github.com/fossasia/loklak_EmojiTracker (Category: Visualizer)

**Comment by KukkadapuSushma** [comment]
I would like to contribute!

**Comment by jig08** [comment]
@KukkadapuSushma As mentioned several times, please resolve previous issues assigned to you before taking up new ones. Thanks :)

**Comment by KukkadapuSushma** [comment]
@jig08  -- I have fixed https://github.com/fossasia/apps.loklak.org/pull/96 - #88 , so want to go ahead with this.

**Comment by KukkadapuSushma** [comment]
@mariobehling , Kindly mention under which category I should include these new apps?

**Comment by mariobehling** [comment]
@KukkadapuSushma Added the categories in the description, that I think are most suitable, but if you have other ideas feel free to change it. Thanks!

**Comment by KukkadapuSushma** [comment]
Status : Done with three apps, will finish off soon! :)

**Comment by mariobehling** [comment]
@KukkadapuSushma Please make a PR for the apps you got done already. This might help to get others on board and speed up our development engagement.

**Comment by KukkadapuSushma** [comment]
https://github.com/fossasia/loklak_EmojiTracker : the last app seems to be under development. @mariobehling , And, there's no sample screenshot of it add. So, should i create PR with only 5 apps out of 6 you have mentioned !?

**Comment by KukkadapuSushma** [comment]
https://github.com/fossasia/apps.loklak.org/pull/103

**Comment by daminisatya** [comment]
@KukkadapuSushma great, i reviewed your PR and merged, please mark those apps which are done. thank you

**Comment by KukkadapuSushma** [comment]
@mariobehling -- Kindly have a look it this issue !

**Comment by KukkadapuSushma** [comment]
https://github.com/fossasia/loklak_heatmap (Category: Visualizer) --- Neglecting this python based app for now, and i see https://github.com/fossasia/loklak_tweetheatmap (Category: Visualizer) is working!!

So, i am left with only "EmohiTrackerApp" -- but I see that its still under development.

@mariobehling
